version: '2'
services:
  db:
    build: ./mysql
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=verysecret
      - MYSQL_DATABASE=notes
      - MYSQL_USER=notes-api
      - MYSQL_PASSWORD=notes-api

    volumes:
      - /data/mysql:/var/lib/mysql
  app:
    build: ./app
    environment:
      NODE_ENV: production
    ports:
      - '8888:8888'
    links:
      - db 
       
  web:
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /www/public
    volumes_from:
      - app
    links:
      - app
