---
#- name: instalar do pacote repo.
#  yum_repository:
#    name: centos
#    description: DOCKER YUM repo
#    baseurl: https://download.docker.com/linux/centos/docker-ce.repo
#    enable: yes
- name: DOCKER -instalar repo docker
  shell: sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo & sudo yum-config-manager --enable docker-ce-edge & sudo yum-config-manager --enable docker-ce-test

- name: instalar do pacote repo.
  yum:
    name: epel-release

- name: DOCKER -instalação de pacotes e dependencias.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
#    - yum-utils
    - lvm2
    - device-mapper-persistent-data
    - python-pip
    - net-tools
    - vim
    - docker-ce
  notify:
    - enable docker

- name: DOCKER -instalar pacote docker-py.
  pip:
    name: docker-py

- name: DOCKER-COMPOSE -instalar repo docker-compose.
  shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose 

- name: DOCKER-COMOSE -configurar binario.
  shell: sudo chmod +x /usr/local/bin/docker-compose 

- name: DOCKER -criar grupo docker.
  group:
    name: "{{group_user}}"
    state: present

- name: DOCKER -adicionar usuario vagrant no grupo docker.
  shell: "sudo usermod -aG docker {{sys_user}}"

#- name: adicionar usuario de serviço.
#  user:
#    name: "{{sys_user}}"
#    shell: "/bin/bash" 
#    home: "{{path_sys}}"
#    groups: "{{group_user}}"
#    append: yes

- name: DOCKER -alterar arquivo de configuração do docker
  template:
    src: docker.j2  
    dest: /etc/sysconfig/docker
    backup: yes
  notify:
   - restart docker

- name: DOCKER_COMPOSE -criar diretorio para docker compose.
  file:
    path: "{{path_sys}}/docker-compose"
    owner: "{{sys_user}}"
    group: "{{group_user}}"
    mode: 0775
    state: directory
  when: sys_user is defined

- name: DOCKER -force restart docker
  shell: sudo service docker restart
